feat: added package implementation
sapphiredev/create-sapphire-bot pull request #1
Opened 2021-05-08 01:28 UTC by kyranet

2021-05-08 20:59 UTC, Favna requested changes

2021-05-08 20:59 UTC, Favna commented on src/cli.ts
> +		console.log(`${indent3}${gray(`- ${bold('--module')} is ${bold('cjs')}`)}`);
I feel like there must be a better way to do this. Like with a custom logging function that just takes an array of contents and maps it to `console.log`.

2021-05-08 20:59 UTC, Favna commented on src/lib/filesystem/Creator.ts
> +		},
```suggestion
```

Using commitlint, lint-staged and commitizen is heavily opinionated and not needed tbh.

2021-05-08 20:59 UTC, Favna commented on src/lib/filesystem/Creator.ts
> +}
Why not use [`@sapphire/fetch`](https://github.com/sapphiredev/utilities/tree/main/packages/fetch)

2021-05-08 20:59 UTC, Favna commented on src/lib/filesystem/Creator.ts
> +	const url = new URL(`https://registry.yarnpkg.com/${encodeURIComponent(name)}`);
```suggestion
	const url = new URL(`https://registry.npmjs.com/${encodeURIComponent(name)}`);
```

2021-05-08 20:59 UTC, Favna commented on src/lib/replacers/IReplacer.ts
> +export abstract class IReplacer {
Either dismiss the codeql alerts or resolve them

2021-05-08 20:59 UTC, Favna commented on src/templates/javascript.ts
> +		'lint-staged'
```suggestion
		'@sapphire/eslint-config',
		'@sapphire/prettier-config',
		'@sapphire/ts-config'
```

See other comment about hooks and such. And we can remove prettier because it is a dependency of the 2 configs.

2021-05-08 20:59 UTC, Favna commented on src/templates/javascript.ts
> +		prepare: 'husky install .github/husky'
```suggestion
		format: 'prettier --write src/**/*.js'
```

2021-05-08 20:59 UTC, Favna commented on src/templates/javascript.ts
> +		.add('.gitattributes', '* text eol=lf')
```suggestion
```

This line is dangerous because it changes everything. The only way can work safely is by also adding all the other lines that are in Skyra's repo, specifically those that specify images and the like to be binaries. That said, the better solution is to just remove `.gitattributes` all together for writing line endings.

Not to mention that we shouldn't be forcing line endings on people.

2021-05-08 20:59 UTC, Favna commented on src/templates/javascript.ts
> +		.add('tsconfig.base.json', ['{', '	"extends": "@sapphire/ts-config"', '}'])
```suggestion
```

This is the JavaScript template

2021-05-08 20:59 UTC, Favna commented on src/templates/javascript.ts
> +		.add('tsconfig.eslint.json', ['{', '	"extends": "./tsconfig.base.json",', '	"include": ["src"]', '}'])
```suggestion
		.add('tsconfig.eslint.json', ['{', '	"extends": "@sapphire/ts-config",', '	"include": ["src"]', '}'])
```

2021-05-08 20:59 UTC, Favna commented on src/templates/typescript.ts
> +		prepare: 'husky install .github/husky',
```suggestion
		lint: 'eslint src --ext ts --fix',
		format: 'prettier --write src/**/*.ts'
```

2021-05-08 20:59 UTC, Favna commented on src/templates/typescript.ts
> +		'typescript'
```suggestion
		'@sapphire/eslint-config',
		'@sapphire/prettier-config',
		'@sapphire/ts-config',
		'@types/node',
		'@types/ws',
		'typescript'
```

2021-05-08 20:59 UTC, Favna commented on src/templates/typescript.ts
> +		.add('.gitattributes', '* text eol=lf')
```suggestion
```

2021-05-08 20:59 UTC, Favna commented on src/templates/typescript.ts
> +					'		client.logger.fatal(error);',
This needs binding logger remember

2021-05-08 21:01 UTC, kyranet commented on src/templates/typescript.ts
> +					'		client.logger.fatal(error);',
No, it doesn't, Skyra's issue was that we were doing `client.login().catch(client.logger.fatal);`, this is different.

2021-05-08 21:02 UTC, Favna requested changes

2021-05-08 21:02 UTC, Favna commented on .github/CONTRIBUTING.md
> +-   Everything in @sapphire/create-sapphire-bot should be generally useful for the majority of users. Don't let that stop you if you've got a good concept though, as your idea still might be a great
```suggestion
-   Everything in create-sapphire-bot should be generally useful for the majority of users. Don't let that stop you if you've got a good concept though, as your idea still might be a great addition.
```

The whole point of `create-` prefix is that it is unscoped, otherwise `yarn create sapphire-bot` still wont work.

2021-05-08 21:02 UTC, Favna commented on README.md
> +# @sapphire/create-sapphire-bot
```suggestion
# create-sapphire-bot
```

2021-05-08 21:02 UTC, Favna commented on README.md
> +[![Depfu](https://badges.depfu.com/badges/create-sapphire-bot/count.svg)](https://depfu.com/github/sapphiredev/e?project_id=create-sapphire-bot)
```suggestion
[![Depfu](https://badges.depfu.com/badges/001ad288408da435422d7d97b733469b/count.svg)](https://depfu.com/github/sapphiredev/create-sapphire-bot?project_id=25517)
```

2021-05-08 21:02 UTC, Favna commented on README.md
> +[![codecov](https://codecov.io/gh/sapphiredev/sapphire-create-sapphire-bot/branch/main/graph/badge.svg?token=0MSAyoZNxz)](https://codecov.io/gh/sapphiredev/sapphire-create-sapphire-bot)
```suggestion
[![codecov](https://codecov.io/gh/sapphiredev/create-sapphire-bot/branch/main/graph/badge.svg?token=WMt3CM4qW4)](https://codecov.io/gh/sapphiredev/create-sapphire-bot)
```

2021-05-08 21:02 UTC, Favna commented on guides/getting-started/GettingStarted.mdx
> +export const name = '@sapphire/create-sapphire-bot';
```suggestion
export const name = 'create-sapphire-bot';
```

2021-05-08 21:02 UTC, Favna commented on package.json
> +	"name": "@sapphire/create-sapphire-bot",
```suggestion
	"name": "create-sapphire-bot",
```

2021-05-08 21:02 UTC, Favna commented on package.json
> +	},
```suggestion
	"bin": {
		"create-sapphire-bot": "./dist/cli.js"
		"csb": "./dist/cli.js"
	},
```

short aliases are always pog

2021-05-08 21:02 UTC, Favna commented on typedoc.json
> +	"name": "@sapphire/create-sapphire-bot",
```suggestion
	"name": "create-sapphire-bot",
```

2021-05-08 21:03 UTC, Favna requested changes
This needs advanced CI. Jest tests to test the actual API is one thing, but we should also run the CLI and validate the output.

NOTE: This also means it has to be possible to generate a full template non-interactively. 
This means supporting flags.
I didn't check if every option is passable as flags
If not, add that

Basic idea:

```yaml
name: Template Verification

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  JavaScriptCjsTemplate:
    name: Validate JavaScript CommonJS DiscordJS Template Node v${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12, 14, 15, 16]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Use Node.js v${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Restore CI Cache
        uses: actions/cache@v2.1.5
        id: cache-restore
        with:
          path: node_modules
          key: ${{ matrix.os }}-${{ matrix.node_version }}-${{ hashFiles(matrix.os == 'windows-latest' && '**\yarn.lock' || '**/yarn.lock') }}
      - name: Install Dependencies if Cache Miss
        if: ${{ !steps.cache-restore.outputs.cache-hit }}
        run: yarn --frozen-lockfile
      - name: Generate template
        run: INSERT COMMAND TO GENERATE JAVASCRIPT TEMPLATE HERE
      - name: Validate template
        run: |
          # Various bash or node scripts here to validate all the output.
          # Use things like `ls` with `grep`
          # Or write a script in mjs to validate it and put that in `/scripts`

  JavaScriptEsmTemplate:
    name: Validate JavaScript ESM DiscordJS Template Node v${{ matrix.node }}
# etc

  TypeScriptCjsTemplate:
    name: Validate TypeScript CommonJS DiscordJS Template Node v${{ matrix.node }}
# etc

  TypeScriptEsmTemplate:
    name: Validate TypeScript ESM DiscordJS Template Node v${{ matrix.node }}
# etc
```

2021-05-08 21:11 UTC, kyranet commented on src/lib/filesystem/Creator.ts
> +}
I wanted to go low on dependencies, and this little helper does the job very well.

2021-05-08 21:21 UTC, kyranet commented on src/lib/replacers/IReplacer.ts
> +export abstract class IReplacer {
Resolved in 8333b7b.

2021-05-09 12:07 UTC, vladfrangu requested changes

2021-05-09 12:07 UTC, vladfrangu commented on src/lib/shared.ts
> +export type Extension = '.js' | '.cjs' | '.mjs';
Where .ts

2021-05-09 12:07 UTC, vladfrangu commented on src/templates/typescript.ts
> +					'const main = async () => {',
```suggestion
					'async function main() {',
```

2021-05-09 12:07 UTC, vladfrangu commented on src/templates/typescript.ts
> +				])
```suggestion
				]) // src/tsconfig.json
```

2021-05-09 12:13 UTC, kyranet commented on src/cli.ts
> +import { existsSync } from 'fs';
Probably because fs/promises doesn't have exists

2021-05-09 12:16 UTC, vladfrangu commented
Could use stat instead

On Sun, 9 May 2021 at 15:13, Antonio Román ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/cli.ts
> <https://github.com/sapphiredev/create-sapphire-bot/pull/1#discussion_r628881991>
> :
>
> > @@ -0,0 +1,169 @@
> +#!/usr/bin/env node
> +
> +import { exec } from 'child_process';
> +import { bold, cyan, gray, green, red } from 'colorette';
> +import { Command } from 'commander';
> +import { existsSync } from 'fs';
>
> Probably because fs/promises doesn't have exists
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/sapphiredev/create-sapphire-bot/pull/1#discussion_r628881991>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEJA4MC4IUF6KQWFYVDVADTTMZ37NANCNFSM44L4VVRQ>
> .
>

2021-05-10 19:58 UTC, Favna requested changes

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
>        - name: Run ESLint
Add cache skipping, see other repos.

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
>          run: yarn --frozen-lockfile
Ditto

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
> +      - name: Use Node.js 16
```suggestion
      - name: Use Node.js v16
```

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
> +      - name: Use Node.js 16
```suggestion
      - name: Use Node.js v16
```

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
> +      - name: Use Node.js 16
```suggestion
      - name: Use Node.js v16
```

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
>          run: yarn --ignore-scripts --frozen-lockfile
![](https://play.pokemonshowdown.com/sprites/ani/ditto.gif)

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
>          run: yarn --ignore-scripts --frozen-lockfile
```suggestion
        run: yarn --frozen-lockfile
```

2021-05-10 19:58 UTC, Favna commented on .github/workflows/continuous-integration.yml
>          run: yarn --ignore-scripts --frozen-lockfile
```suggestion
        run: yarn --frozen-lockfile
```

2021-05-10 19:58 UTC, Favna commented on src/templates/typescript.ts
> +		format: 'prettier --write src/**/*.ts',
```suggestion
		format: 'prettier --write \\"src/**/*.ts\\"',
```

Or whatever outputs `\"` in the JSON. Bit of a wildcard quirk but (see https://prettier.io/docs/en/cli.html) but this way it is ensured that the wildcards can be resolved by Prettier's globber instead of the OS. Thus providing a proper cross-platform script.

So this final script in `package.json` should be:
```json
{
  "format": "prettier --write \"src/**/*.ts\""
}
```

2021-05-10 19:58 UTC, Favna commented on src/templates/javascript.ts
> +		format: 'prettier --write src/**/*.js'
![](https://play.pokemonshowdown.com/sprites/ani/ditto.gif) comment on the TS template

2021-05-10 19:58 UTC, Favna commented on tests/lib/filesystem/Creator.test.ts
> +			format: 'prettier --write src/**/*.js'
This should fail after resolving earlier comment

2021-05-11 20:42 UTC, Favna approved these changes

2021-05-11 20:42 UTC, merged